---
title: 'Assignment 1: Create and Visualise'
author: "Simon van Baal"
date: "`r Sys.Date()`"
output: html_document
---

## Create a dataset

Thanks for going through the painful process of downloading Git and sorting out GitHub. 

Always open the README file first when you access a project - it will tell you
how to get started.

Here's the assignment:

You have access to the "create-data_mischel1972_tewa1.Rmd" file, where you see
how I created some data loosely based on the information provided in this paper:

Mischel, W., Ebbesen, E. B., & Raskoff Zeiss, A. (1972). Cognitive and attentional mechanisms in delay of gratification. Journal of Personality and Social Psychology, 21(2), 204–218. https://doi.org/10.1037/h0032198

Please read the Methods section for Experiment 2 and visualise the data based
on an estimate eye-balling the Figure. 

To do this: 
1. Create a new R Markdown file, in the top left of the RStudio window.
2. Iteratively copy commands from the "create...Rmd file" and amend them to
suit your assignment.
3. Use ggplot2 to create plots of the data.

When you are done, "Knit" your R Markdown file so you can show it to everyone.

Pay attention to how I organised this directory - it helps make it so things 
don't get lost. 

## Tips
Some useful tips that will help you work easier with R:

- You can start a new chunk by pressing Ctrl+Alt+I (Mac: CMD+Opt+I). 

- You can run a line by putting your cursor on the line and pressing Ctrl+Enter.

- Good formatting of your code will help with readability. If you would like R to
format a bunch of code for you, sorting out indentation and the like, press:
Ctrl+Shift+A while selecting a bit of code.

- You can make R not run code by selecting a bunch of it and pressing 
Ctrl+Shift+C. If you press this again, it removes the "#", which will un-comment
your code.

- Code chunks have options - useful ones tend to be include = TRUE/FALSE and 
echo = TRUE/FALSE.

